ci: fix linter  (#33)
* test(#19): integration test for login endpoint

* test(#19): integration tests for register endpoint

* test(#19): integration test for register endpoint (#25)

* refacotr(authentication): [WIP] split authentication methods to custom class #19

* fix(LIL-2865): update sample file for pix

* refactor: improve readability

* test(#19): integration test for login endpoint

* refacotr(#19):split authentication methods to custom class #19

* refactor(#19): move folder dependency

* test(#19): integration tests for register endpoint

Co-authored-by: Aristide Herve Mbassi <aristideherve.mbassidemoudourou@veepee.comm>

* test(#19): test confirm email endpoint

* refactor(#19): use pgsqlbuilder

* style: format code

* test(#19): run test sequentialty

* ci: add linter for commit to follow conventionnal commit pattern

* ci: fix husy commit linter

---------

Co-authored-by: Aristide Herve Mbassi <aristideherve.mbassidemoudourou@veepee.comm>

diff --git a/.github/workflows/commit-lint.yml b/.github/workflows/commit-lint.yml
--- a/.github/workflows/commit-lint.yml
+++ b/.github/workflows/commit-lint.yml
@@ -1,43 +1,44 @@
-name: "Validate commit messages"
+name: Validate Commit Messages
 
 on:
   pull_request:
-    types: [ opened, synchronize, reopened ]
+    types: [opened, synchronize, reopened]
   push:
-    branches: [ main, develop ]
-  
-  
-  jobs:
-    validate-commit-message:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout out code
-          uses: actions/checkout@v4
-          with:
-            fetch-depth: 0
-        
-        - name: Validate commit messages
-          run: |
-            #!/bin/bash
-            set -e
-            # The regex pattern for commit messages
-            pattern='^(?=.{1,90}$)(?:feat|feat!|chore|ci|build|docs|fix|perf|refactor|revert|style|test|wip)(?:\(.+\))*(?::).{4,}(?:#\d+)*(?<![\.\s])$'
-            # Get the commits to validate
-                    if [[ "${{ github.event_name }}" == "pull_request" ]]; then
-                      commits=$(git log --format=%s ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
-                    else
-                      commits=$(git log --format=%s -n 1)
-                    fi
+    branches: [main, master]
 
-                    # Validate each commit message
-                    while read -r commit_msg; do
-                      if ! [[ $commit_msg =~ $pattern ]]; then
-                        echo "Invalid commit message: $commit_msg"
-                        echo "Commit messages must follow the pattern: <type>(<scope>): <description> [#<issue-number>]"
-                        echo "Types: feat, feat!, chore, ci, build, docs, fix, perf, refactor, revert, style, test, wip"
-                        exit 1
-                      fi
-                    done <<< "$commits"
+jobs:
+  validate-commits:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
-                    echo "All commit messages are valid!"
-          shell: bash
+      - name: Validate commit messages
+        run: |
+          #!/bin/bash
+          set -e
+          
+          # The regex pattern for commit messages
+          pattern='^(?=.{1,90}$)(?:feat|feat!|chore|ci|build|docs|fix|perf|refactor|revert|style|test|wip)(?:\(.+\))*(?::).{4,}(?:#\d+)*(?<![\.\s])$'
+          
+          # Get the commits to validate
+          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+            commits=$(git log --format=%s ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
+          else
+            commits=$(git log --format=%s -n 1)
+          fi
+          
+          # Validate each commit message
+          while read -r commit_msg; do
+            if ! [[ $commit_msg =~ $pattern ]]; then
+              echo "Invalid commit message: $commit_msg"
+              echo "Commit messages must follow the pattern: <type>(<scope>): <description> [#<issue-number>]"
+              echo "Types: feat, feat!, chore, ci, build, docs, fix, perf, refactor, revert, style, test, wip"
+              exit 1
+            fi
+          done <<< "$commits"
+          
+          echo "All commit messages are valid!"
+        shell: bash
